language: python

dist: trusty
sudo: required

services:
  - docker

matrix:
  include:
    - python: "2.7"
      env:
        - TOX_ENV=py27,flake8
    - python: "3.4"
      env:
        - TOX_ENV=py34,flake8
    - python: "3.5"
      env:
        - TOX_ENV=py35,flake8

install:
  - pip install tox
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - tox -e $TOX_ENV
